language: rust

rust:
  - stable

cache: cargo

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-pc-windows-gnu
      os: windows

script:
  - cargo build --release
